/**
 * Europe Daily Phrases — language data
 *
 * Every speakable item keeps an audioUrl field. Add a local/remote audio URL
 * to prefer recorded audio; leave it empty to use the Web Speech API.
 */

const CATEGORY_LABELS = Object.freeze({
  all: "全部",
  greetings: "招呼",
  polite: "禮貌",
  travel: "旅行",
  restaurant: "餐廳",
  transport: "交通",
  accommodation: "住宿",
});

const alphabetItem = (text, name, pronunciation, speechText, note = "") => ({
  text,
  name,
  pronunciation,
  speechText,
  note,
  audioUrl: "",
});

const GERMAN_LETTER_SPEECH = Object.freeze({
  A: "ah",
  B: "beh",
  C: "zeh",
  D: "deh",
  E: "eh",
  F: "eff",
  G: "geh",
  H: "ha",
  I: "ih",
  J: "jott",
  K: "kah",
  L: "ell",
  M: "emm",
  N: "enn",
  O: "oh",
  P: "peh",
  Q: "kuh",
  R: "err",
  S: "ess",
  T: "teh",
  U: "uh",
  V: "fau",
  W: "weh",
  X: "iks",
  Y: "Ypsilon",
  Z: "zett",
  Ä: "äh",
  Ö: "öh",
  Ü: "üh",
  ß: "Eszett",
});

// Keep alphabet speechText as the spoken letter name only.
// Raw uppercase characters may make some system voices add an unwanted prefix.
const swedishLetter = (text, name, pronunciation, note = "") =>
  alphabetItem(text, name, pronunciation, name, note);

const germanLetter = (text, name, pronunciation, note = "") =>
  alphabetItem(text, name, pronunciation, GERMAN_LETTER_SPEECH[text], note);

const italianLetter = (text, name, pronunciation, note = "") =>
  alphabetItem(text, name, pronunciation, text === "V" ? "vi" : name, note);

const phraseItem = (id, category, meaning, text, pronunciation, context) => ({
  id,
  category,
  meaning,
  text,
  pronunciation,
  context,
  speechText: text,
  audioUrl: "",
});

const numberRuleItem = (
  value,
  text,
  meaning,
  pronunciation,
  formula = "",
  note = "",
  category = "number",
  speechText = text,
) => ({
  value,
  text,
  meaning,
  pronunciation,
  speechText,
  formula,
  note,
  category,
  audioUrl: "",
});

const decimalExample = (value, text, meaning, note) => ({
  value,
  text,
  meaning,
  pronunciation: "",
  speechText: text,
  note,
  category: "decimal",
  audioUrl: "",
});

const LANGUAGE_DATA = {
  swedish: {
    label: "瑞典語",
    nativeName: "Svenska",
    flag: "🇸🇪",
    speechLang: "sv-SE",
    voiceName: "Alva",
    accent: "swedish",
    alphabetNote: "瑞典語共有 29 個字母；Å、Ä、Ö 是獨立字母，排在 Z 之後。",
    alphabet: [
      swedishLetter("A", "a", "啊"),
      swedishLetter("B", "be", "貝"),
      swedishLetter("C", "se", "塞"),
      swedishLetter("D", "de", "得"),
      swedishLetter("E", "e", "欸"),
      swedishLetter("F", "eff", "艾夫"),
      swedishLetter("G", "ge", "耶／給"),
      swedishLetter("H", "hå", "霍"),
      swedishLetter("I", "i", "伊"),
      swedishLetter("J", "ji", "依"),
      swedishLetter("K", "kå", "科"),
      swedishLetter("L", "ell", "艾爾"),
      swedishLetter("M", "em", "艾姆"),
      swedishLetter("N", "en", "恩"),
      swedishLetter("O", "o", "烏／歐"),
      swedishLetter("P", "pe", "佩"),
      swedishLetter("Q", "ku", "庫"),
      swedishLetter("R", "ärr", "艾爾（顫音）"),
      swedishLetter("S", "ess", "艾斯"),
      swedishLetter("T", "te", "特"),
      swedishLetter("U", "u", "於"),
      swedishLetter("V", "ve", "維"),
      swedishLetter("W", "dubbel-ve", "杜貝爾維"),
      swedishLetter("X", "eks", "艾克斯"),
      swedishLetter("Y", "y", "圓唇「於」"),
      swedishLetter("Z", "säta", "塞塔"),
      swedishLetter("Å", "å", "喔"),
      swedishLetter("Ä", "ä", "欸"),
      swedishLetter("Ö", "ö", "圓唇「呃」"),
    ],
    phrases: [
      phraseItem("hello", "greetings", "你好", "Hej!", "嗨／嘿", "最通用的日常招呼。"),
      phraseItem("good-morning", "greetings", "早安", "God morgon!", "咕・摩榮", "早晨向人打招呼。"),
      phraseItem("good-afternoon", "greetings", "午安／下午好", "God eftermiddag!", "咕・艾夫特米達格", "午後較正式的招呼。"),
      phraseItem("good-evening", "greetings", "晚上好", "God kväll!", "咕・克維爾", "傍晚或夜間見面時。"),
      phraseItem("good-night", "greetings", "晚安", "God natt!", "咕・納特", "睡前或夜晚道別。"),
      phraseItem("goodbye", "greetings", "再見", "Hej då!", "嗨・多", "常用、自然的道別。"),
      phraseItem("see-you", "greetings", "回頭見", "Vi ses!", "維・塞斯", "和熟人輕鬆道別。"),
      phraseItem("nice-to-meet", "greetings", "很高興認識你", "Trevligt att träffas.", "特雷夫里特・阿特・特雷法斯", "第一次見面時。"),
      phraseItem("please", "polite", "請", "Snälla.", "斯內拉", "請求時使用；點餐常直接搭配 tack。"),
      phraseItem("thanks", "polite", "謝謝", "Tack!", "塔克", "最常用的謝謝。"),
      phraseItem("many-thanks", "polite", "非常謝謝", "Tack så mycket!", "塔克・索・米克特", "加強謝意。"),
      phraseItem("you-are-welcome", "polite", "不客氣", "Varsågod!", "瓦修咕", "回應謝謝，或遞東西給人時。"),
      phraseItem("sorry", "polite", "對不起", "Förlåt.", "佛洛特", "道歉時使用。"),
      phraseItem("excuse-me", "polite", "不好意思／打擾一下", "Ursäkta.", "烏謝克塔", "引起注意、借過或詢問前。"),
      phraseItem("no-problem", "polite", "沒關係", "Ingen fara.", "英恩・法拉", "表示不用擔心。"),
      phraseItem("speak-english", "travel", "請問你會說英文嗎？", "Talar du engelska?", "塔拉・杜・英耶爾斯卡", "需要改用英文溝通時。"),
      phraseItem("dont-speak-language", "travel", "我不會說瑞典語", "Jag talar inte svenska.", "亞・塔拉・英特・斯文斯卡", "先說明自己的語言能力。"),
      phraseItem("help-me", "travel", "可以請你幫我嗎？", "Kan du hjälpa mig?", "康・杜・耶爾帕・梅", "需要一般協助時。"),
      phraseItem("how-much", "travel", "這個多少錢？", "Hur mycket kostar det här?", "許爾・米克特・庫斯塔・德・海爾", "購物詢價時。"),
      phraseItem("want-this", "travel", "我要這個", "Jag tar den här.", "亞・塔・登・海爾", "購物時指著想要的物品。"),
      phraseItem("order", "restaurant", "我想點餐", "Jag skulle vilja beställa.", "亞・斯庫勒・維利亞・貝斯特拉", "準備點餐時。"),
      phraseItem("menu", "restaurant", "請給我菜單", "Kan jag få menyn, tack?", "康・亞・佛・梅紐恩・塔克", "向服務人員要菜單。"),
      phraseItem("bill", "restaurant", "我要結帳", "Notan, tack.", "努坦・塔克", "用餐後請服務人員結帳。"),
      phraseItem("toilet", "travel", "洗手間在哪裡？", "Var ligger toaletten?", "瓦・利格・圖阿雷滕", "尋找洗手間。"),
      phraseItem("station", "transport", "車站在哪裡？", "Var ligger stationen?", "瓦・利格・斯塔胡嫩", "詢問火車站或車站位置。"),
      phraseItem("lost", "travel", "我迷路了", "Jag har gått vilse.", "亞・哈・果特・維爾瑟", "迷路並需要協助時。"),
      phraseItem("slower", "travel", "請慢一點說", "Kan du prata lite långsammare?", "康・杜・普拉塔・利特・隆薩瑪雷", "對方說得太快時。"),
      phraseItem("repeat", "travel", "可以再說一次嗎？", "Kan du säga det igen?", "康・杜・塞亞・德・伊耶恩", "沒有聽清楚時。"),
      phraseItem("reservation", "accommodation", "我有預約", "Jag har en bokning.", "亞・哈・恩・布克寧", "飯店或餐廳報到時。"),
      phraseItem("go-here", "transport", "我想去這裡", "Jag vill åka hit.", "亞・維爾・歐卡・希特", "指著地圖告訴司機。"),
      phraseItem("call-taxi", "transport", "請幫我叫計程車", "Kan du ringa en taxi åt mig?", "康・杜・林亞・恩・塔克西・歐特・梅", "請櫃檯或店員叫車。"),
      phraseItem("ticket", "transport", "請給我一張到市中心的票", "En biljett till centrum, tack.", "恩・比耶特・提爾・森特魯姆・塔克", "在售票處買票。"),
      phraseItem("platform", "transport", "請問是第幾月台？", "Vilken perrong?", "維爾肯・佩榮", "確認列車月台。"),
      phraseItem("check-in", "accommodation", "我想辦理入住", "Jag skulle vilja checka in.", "亞・斯庫勒・維利亞・謝卡・英", "抵達飯店櫃檯時。"),
      phraseItem("wifi", "accommodation", "這裡有 Wi-Fi 嗎？", "Finns det wifi här?", "芬斯・德・外法以・海爾", "詢問網路服務。"),
      phraseItem("allergy", "restaurant", "我對堅果過敏", "Jag är allergisk mot nötter.", "亞・艾・阿萊爾吉斯克・莫特・內特爾", "用餐前說明過敏。"),
    ],
    numberRules: {
      coreNumbers: [
        numberRuleItem("0", "noll", "零", "諾爾", "", "", "core"),
        numberRuleItem("1", "ett / en", "一", "欸特／恩", "", "單獨數數優先使用 ett。", "core", "ett"),
        numberRuleItem("2", "två", "二", "托沃", "", "", "core"),
        numberRuleItem("3", "tre", "三", "特雷", "", "", "core"),
        numberRuleItem("4", "fyra", "四", "菲拉", "", "", "core"),
        numberRuleItem("5", "fem", "五", "費姆", "", "", "core"),
        numberRuleItem("6", "sex", "六", "塞克斯", "", "", "core"),
        numberRuleItem("7", "sju", "七", "許", "", "", "core"),
        numberRuleItem("8", "åtta", "八", "歐塔", "", "", "core"),
        numberRuleItem("9", "nio", "九", "尼歐", "", "", "core"),
        numberRuleItem("10", "tio", "十", "提歐", "", "", "core"),
        numberRuleItem("11", "elva", "十一", "艾爾瓦", "", "", "core"),
        numberRuleItem("12", "tolv", "十二", "托爾夫", "", "", "core"),
        numberRuleItem("13", "tretton", "十三", "特雷通", "", "", "core"),
        numberRuleItem("14", "fjorton", "十四", "菲尤通", "", "", "core"),
        numberRuleItem("15", "femton", "十五", "費姆通", "", "", "core"),
        numberRuleItem("16", "sexton", "十六", "塞克斯通", "", "", "core"),
        numberRuleItem("17", "sjutton", "十七", "許通", "", "", "core"),
        numberRuleItem("18", "arton", "十八", "阿通", "", "", "core"),
        numberRuleItem("19", "nitton", "十九", "尼通", "", "", "core"),
      ],
      tens: [
        numberRuleItem("20", "tjugo", "二十", "許果", "", "", "tens"),
        numberRuleItem("30", "trettio", "三十", "特雷提歐", "", "", "tens"),
        numberRuleItem("40", "fyrtio", "四十", "菲提歐", "", "", "tens"),
        numberRuleItem("50", "femtio", "五十", "費姆提歐", "", "", "tens"),
        numberRuleItem("60", "sextio", "六十", "塞克斯提歐", "", "", "tens"),
        numberRuleItem("70", "sjuttio", "七十", "許提歐", "", "", "tens"),
        numberRuleItem("80", "åttio", "八十", "歐提歐", "", "", "tens"),
        numberRuleItem("90", "nittio", "九十", "尼提歐", "", "", "tens"),
        numberRuleItem("100", "hundra", "一百", "亨德拉", "", "", "tens"),
      ],
      rules: [
        {
          title: "基本組合方向",
          formula: "十位數 + 個位數",
          description: "瑞典語 21 以後通常由十位數接個位數，中間不用加 and，寫成一個字。",
        },
        { title: "21", formula: "tjugo + ett → tjugoett", description: "二十加一。" },
        { title: "22", formula: "tjugo + två → tjugotvå", description: "二十加二。" },
        { title: "35", formula: "trettio + fem → trettiofem", description: "三十加五。" },
        { title: "48", formula: "fyrtio + åtta → fyrtioåtta", description: "四十加八。" },
        { title: "99", formula: "nittio + nio → nittionio", description: "九十加九。" },
      ],
      exceptions: [
        { title: "1 的兩種形式", text: "1 有 ett / en，單獨數數常用 ett。" },
        { title: "20 要單獨記", text: "20 是 tjugo，不是 två + tio。" },
        { title: "不規則十位", text: "30 trettio、40 fyrtio 是需要另外記的十位數。" },
        { title: "方向像中文", text: "瑞典語數字組合方向和中文接近，是「二十 + 一」。" },
      ],
      decimalRules: {
        separatorName: "komma",
        separatorSymbol: ",",
        readingRule: "整數 + komma + 小數部分",
        description: "日常價格、尺寸或數值中，小數逗號後可以依情境讀成一個數字，也可以逐位讀出。學習者優先理解 komma 即可。",
        examples: [
          decimalExample("3,14", "tre komma fjorton", "三點一四", "小數逗號後可依情境讀成一整個數字或逐位讀出；逐位也可說 tre komma ett fyra。"),
          decimalExample("1,5", "ett komma fem", "一點五", "相當於中文的小數點。"),
          decimalExample("0,8", "noll komma åtta", "零點八", "相當於中文的小數點。"),
          decimalExample("12,75", "tolv komma sjuttiofem", "十二點七五", "小數部分也可依情境逐位讀出。"),
        ],
      },
      examples: [
        numberRuleItem("21", "tjugoett", "二十一", "許果・欸特", "tjugo + ett", "十位數接個位數。", "example"),
        numberRuleItem("22", "tjugotvå", "二十二", "許果・托沃", "tjugo + två", "", "example"),
        numberRuleItem("28", "tjugoåtta", "二十八", "許果・歐塔", "tjugo + åtta", "", "example"),
        numberRuleItem("31", "trettioett", "三十一", "特雷提歐・欸特", "trettio + ett", "", "example"),
        numberRuleItem("35", "trettiofem", "三十五", "特雷提歐・費姆", "trettio + fem", "", "example"),
        numberRuleItem("48", "fyrtioåtta", "四十八", "菲提歐・歐塔", "fyrtio + åtta", "", "example"),
        numberRuleItem("57", "femtiosju", "五十七", "費姆提歐・許", "femtio + sju", "", "example"),
        numberRuleItem("81", "åttioett", "八十一", "歐提歐・欸特", "åttio + ett", "", "example"),
        numberRuleItem("88", "åttioåtta", "八十八", "歐提歐・歐塔", "åttio + åtta", "", "example"),
        numberRuleItem("99", "nittionio", "九十九", "尼提歐・尼歐", "nittio + nio", "", "example"),
      ],
    },
  },

  german: {
    label: "德語",
    nativeName: "Deutsch",
    flag: "🇩🇪",
    speechLang: "de-DE",
    voiceName: "Anna",
    accent: "german",
    alphabetNote: "德語使用 26 個基本字母，另有 Ä、Ö、Ü 與 ß（Eszett）。",
    alphabet: [
      germanLetter("A", "a", "啊"),
      germanLetter("B", "be", "貝"),
      germanLetter("C", "tse", "采"),
      germanLetter("D", "de", "得"),
      germanLetter("E", "e", "欸"),
      germanLetter("F", "eff", "艾夫"),
      germanLetter("G", "ge", "給"),
      germanLetter("H", "ha", "哈"),
      germanLetter("I", "i", "伊"),
      germanLetter("J", "jot", "優特"),
      germanLetter("K", "ka", "卡"),
      germanLetter("L", "ell", "艾爾"),
      germanLetter("M", "em", "艾姆"),
      germanLetter("N", "en", "恩"),
      germanLetter("O", "o", "歐"),
      germanLetter("P", "pe", "佩"),
      germanLetter("Q", "ku", "庫"),
      germanLetter("R", "err", "艾爾（小舌音）"),
      germanLetter("S", "ess", "艾斯"),
      germanLetter("T", "te", "特"),
      germanLetter("U", "u", "烏"),
      germanLetter("V", "fau", "法奧"),
      germanLetter("W", "we", "維"),
      germanLetter("X", "iks", "伊克斯"),
      germanLetter("Y", "Ypsilon", "于普西隆"),
      germanLetter("Z", "zett", "采特"),
      germanLetter("Ä", "Ä", "短「欸」"),
      germanLetter("Ö", "Ö", "圓唇「呃」"),
      germanLetter("Ü", "Ü", "圓唇「伊」"),
      germanLetter("ß", "Eszett", "艾斯采特"),
    ],
    phrases: [
      phraseItem("hello", "greetings", "你好", "Hallo!", "哈囉", "最通用的日常招呼。"),
      phraseItem("good-morning", "greetings", "早安", "Guten Morgen!", "古騰・摩根", "早晨向人打招呼。"),
      phraseItem("good-afternoon", "greetings", "午安／下午好", "Guten Tag!", "古騰・塔克", "白天通用且禮貌的招呼。"),
      phraseItem("good-evening", "greetings", "晚上好", "Guten Abend!", "古騰・阿本特", "傍晚或夜間見面時。"),
      phraseItem("good-night", "greetings", "晚安", "Gute Nacht!", "古特・納赫特", "睡前或夜晚道別。"),
      phraseItem("goodbye", "greetings", "再見", "Auf Wiedersehen!", "奧夫・維德澤恩", "較正式的道別。"),
      phraseItem("see-you", "greetings", "回頭見", "Bis später!", "比斯・施佩特", "和熟人輕鬆道別。"),
      phraseItem("nice-to-meet", "greetings", "很高興認識你", "Freut mich, Sie kennenzulernen.", "弗洛伊特・米希・西・肯嫩楚勒嫩", "第一次見面時的禮貌說法。"),
      phraseItem("please", "polite", "請", "Bitte.", "比特", "請求、回應謝謝都可使用。"),
      phraseItem("thanks", "polite", "謝謝", "Danke!", "當克", "最常用的謝謝。"),
      phraseItem("many-thanks", "polite", "非常謝謝", "Vielen Dank!", "菲倫・當克", "加強謝意。"),
      phraseItem("you-are-welcome", "polite", "不客氣", "Gern geschehen!", "給恩・格謝恩", "回應別人的謝謝。"),
      phraseItem("sorry", "polite", "對不起", "Es tut mir leid.", "艾斯・圖特・米爾・萊特", "較完整、真誠的道歉。"),
      phraseItem("excuse-me", "polite", "不好意思／打擾一下", "Entschuldigung.", "恩特舒爾迪貢", "引起注意、借過或道歉。"),
      phraseItem("no-problem", "polite", "沒關係", "Kein Problem.", "凱因・普羅布雷姆", "表示不用在意。"),
      phraseItem("speak-english", "travel", "請問你會說英文嗎？", "Sprechen Sie Englisch?", "施普雷亨・西・英格利施", "禮貌詢問能否改用英文。"),
      phraseItem("dont-speak-language", "travel", "我不會說德語", "Ich spreche kein Deutsch.", "伊希・施普雷赫・凱因・多伊奇", "先說明自己的語言能力。"),
      phraseItem("help-me", "travel", "可以請你幫我嗎？", "Können Sie mir helfen?", "克嫩・西・米爾・黑爾芬", "需要一般協助時。"),
      phraseItem("how-much", "travel", "這個多少錢？", "Wie viel kostet das?", "維・菲爾・科斯特・達斯", "購物詢價時。"),
      phraseItem("want-this", "travel", "我要這個", "Ich nehme das.", "伊希・內默・達斯", "購物時指著想要的物品。"),
      phraseItem("order", "restaurant", "我想點餐", "Ich möchte bestellen.", "伊希・默希特・貝施特倫", "準備點餐時。"),
      phraseItem("menu", "restaurant", "請給我菜單", "Die Speisekarte, bitte.", "迪・施拜澤卡特・比特", "向服務人員要菜單。"),
      phraseItem("bill", "restaurant", "我要結帳", "Zahlen, bitte.", "察倫・比特", "用餐後請服務人員結帳。"),
      phraseItem("toilet", "travel", "洗手間在哪裡？", "Wo ist die Toilette?", "沃・伊斯特・迪・托阿雷特", "尋找洗手間。"),
      phraseItem("station", "transport", "車站在哪裡？", "Wo ist der Bahnhof?", "沃・伊斯特・德爾・班霍夫", "詢問火車站位置。"),
      phraseItem("lost", "travel", "我迷路了", "Ich habe mich verirrt.", "伊希・哈伯・米希・菲爾特", "迷路並需要協助時。"),
      phraseItem("slower", "travel", "請慢一點說", "Bitte sprechen Sie langsamer.", "比特・施普雷亨・西・朗薩默", "對方說得太快時。"),
      phraseItem("repeat", "travel", "可以再說一次嗎？", "Können Sie das bitte wiederholen?", "克嫩・西・達斯・比特・維德霍倫", "沒有聽清楚時。"),
      phraseItem("reservation", "accommodation", "我有預約", "Ich habe eine Reservierung.", "伊希・哈伯・艾訥・雷澤菲隆", "飯店或餐廳報到時。"),
      phraseItem("go-here", "transport", "我想去這裡", "Ich möchte hierhin.", "伊希・默希特・希爾欣", "指著地圖告訴司機。"),
      phraseItem("call-taxi", "transport", "請幫我叫計程車", "Können Sie mir ein Taxi rufen?", "克嫩・西・米爾・艾因・塔克西・魯芬", "請櫃檯或店員叫車。"),
      phraseItem("ticket", "transport", "請給我一張到市中心的票", "Eine Fahrkarte ins Zentrum, bitte.", "艾訥・法卡特・因斯・岑特魯姆・比特", "在售票處買票。"),
      phraseItem("platform", "transport", "請問是第幾月台？", "Welches Gleis, bitte?", "維爾赫斯・格萊斯・比特", "確認列車月台。"),
      phraseItem("check-in", "accommodation", "我想辦理入住", "Ich möchte einchecken.", "伊希・默希特・艾因切肯", "抵達飯店櫃檯時。"),
      phraseItem("wifi", "accommodation", "這裡有 Wi-Fi 嗎？", "Gibt es hier WLAN?", "吉普特・艾斯・希爾・威蘭", "詢問網路服務。"),
      phraseItem("allergy", "restaurant", "我對堅果過敏", "Ich bin allergisch gegen Nüsse.", "伊希・賓・阿萊爾吉施・給根・紐瑟", "用餐前說明過敏。"),
    ],
    numberRules: {
      coreNumbers: [
        numberRuleItem("0", "null", "零", "努爾", "", "", "core"),
        numberRuleItem("1", "eins", "一", "艾因斯", "", "", "core"),
        numberRuleItem("2", "zwei", "二", "茲外", "", "", "core"),
        numberRuleItem("3", "drei", "三", "德萊", "", "", "core"),
        numberRuleItem("4", "vier", "四", "菲爾", "", "", "core"),
        numberRuleItem("5", "fünf", "五", "芬夫", "", "", "core"),
        numberRuleItem("6", "sechs", "六", "澤克斯", "", "", "core"),
        numberRuleItem("7", "sieben", "七", "西本", "", "", "core"),
        numberRuleItem("8", "acht", "八", "阿赫特", "", "", "core"),
        numberRuleItem("9", "neun", "九", "諾因", "", "", "core"),
        numberRuleItem("10", "zehn", "十", "澤恩", "", "", "core"),
        numberRuleItem("11", "elf", "十一", "艾爾夫", "", "", "core"),
        numberRuleItem("12", "zwölf", "十二", "茲沃爾夫", "", "", "core"),
        numberRuleItem("13", "dreizehn", "十三", "德萊澤恩", "", "", "core"),
        numberRuleItem("14", "vierzehn", "十四", "菲爾澤恩", "", "", "core"),
        numberRuleItem("15", "fünfzehn", "十五", "芬夫澤恩", "", "", "core"),
        numberRuleItem("16", "sechzehn", "十六", "澤希澤恩", "", "不是 sechszehn。", "core"),
        numberRuleItem("17", "siebzehn", "十七", "西普澤恩", "", "不是 siebenzehn。", "core"),
        numberRuleItem("18", "achtzehn", "十八", "阿赫特澤恩", "", "", "core"),
        numberRuleItem("19", "neunzehn", "十九", "諾因澤恩", "", "", "core"),
      ],
      tens: [
        numberRuleItem("20", "zwanzig", "二十", "茲凡茲希", "", "", "tens"),
        numberRuleItem("30", "dreißig", "三十", "德萊希", "", "不是 dreizig。", "tens"),
        numberRuleItem("40", "vierzig", "四十", "菲爾茲希", "", "", "tens"),
        numberRuleItem("50", "fünfzig", "五十", "芬夫茲希", "", "", "tens"),
        numberRuleItem("60", "sechzig", "六十", "澤希茲希", "", "", "tens"),
        numberRuleItem("70", "siebzig", "七十", "西普茲希", "", "", "tens"),
        numberRuleItem("80", "achtzig", "八十", "阿赫特茲希", "", "", "tens"),
        numberRuleItem("90", "neunzig", "九十", "諾因茲希", "", "", "tens"),
        numberRuleItem("100", "hundert", "一百", "洪德特", "", "", "tens"),
      ],
      rules: [
        {
          title: "基本組合方向",
          formula: "個位數 + und + 十位數",
          description: "德語 21 以後通常先說個位數，再用 und 接十位數；順序和中文不同。",
        },
        { title: "21", formula: "ein + und + zwanzig → einundzwanzig", description: "像「一和二十」。" },
        { title: "22", formula: "zwei + und + zwanzig → zweiundzwanzig", description: "二和二十。" },
        { title: "35", formula: "fünf + und + dreißig → fünfunddreißig", description: "五和三十。" },
        { title: "48", formula: "acht + und + vierzig → achtundvierzig", description: "八和四十。" },
        { title: "99", formula: "neun + und + neunzig → neunundneunzig", description: "九和九十。" },
      ],
      exceptions: [
        { title: "21 用 ein", text: "21 裡面用 ein，不是 eins。" },
        { title: "16 省略 s", text: "16 是 sechzehn，不是 sechszehn。" },
        { title: "17 省略 en", text: "17 是 siebzehn，不是 siebenzehn。" },
        { title: "30 的 ß", text: "30 是 dreißig，不是 dreizig。" },
        { title: "方向要反過來", text: "德語像「一和二十」，請先看個位再看十位。" },
      ],
      decimalRules: {
        separatorName: "Komma",
        separatorSymbol: ",",
        readingRule: "整數 + Komma + 小數部分逐位讀出",
        description: "德語小數逗號後面常逐位讀出，尤其是測量、數據、價格或電話式數字情境。",
        examples: [
          decimalExample("3,14", "drei Komma eins vier", "三點一四", "德語小數逗號後通常逐位讀出。"),
          decimalExample("1,5", "eins Komma fünf", "一點五", "相當於中文的小數點。"),
          decimalExample("0,8", "null Komma acht", "零點八", "相當於中文的小數點。"),
          decimalExample("12,75", "zwölf Komma sieben fünf", "十二點七五", "小數部分逐位讀出。"),
        ],
      },
      examples: [
        numberRuleItem("21", "einundzwanzig", "二十一", "艾因・翁德・茲凡茲希", "ein + und + zwanzig", "21 使用 ein，不是 eins。", "example"),
        numberRuleItem("22", "zweiundzwanzig", "二十二", "茲外・翁德・茲凡茲希", "zwei + und + zwanzig", "", "example"),
        numberRuleItem("28", "achtundzwanzig", "二十八", "阿赫特・翁德・茲凡茲希", "acht + und + zwanzig", "", "example"),
        numberRuleItem("31", "einunddreißig", "三十一", "艾因・翁德・德萊希", "ein + und + dreißig", "個位先說。", "example"),
        numberRuleItem("35", "fünfunddreißig", "三十五", "芬夫・翁德・德萊希", "fünf + und + dreißig", "", "example"),
        numberRuleItem("48", "achtundvierzig", "四十八", "阿赫特・翁德・菲爾茲希", "acht + und + vierzig", "", "example"),
        numberRuleItem("57", "siebenundfünfzig", "五十七", "西本・翁德・芬夫茲希", "sieben + und + fünfzig", "", "example"),
        numberRuleItem("81", "einundachtzig", "八十一", "艾因・翁德・阿赫特茲希", "ein + und + achtzig", "使用 ein。", "example"),
        numberRuleItem("88", "achtundachtzig", "八十八", "阿赫特・翁德・阿赫特茲希", "acht + und + achtzig", "", "example"),
        numberRuleItem("99", "neunundneunzig", "九十九", "諾因・翁德・諾因茲希", "neun + und + neunzig", "", "example"),
      ],
    },
  },

  italian: {
    label: "義大利語",
    nativeName: "Italiano",
    flag: "🇮🇹",
    speechLang: "it-IT",
    voiceName: "Alice",
    accent: "italian",
    alphabetNote: "義大利語主要使用 21 個字母。J、K、W、X、Y 多見於外來語、名字或品牌。",
    alphabet: [
      italianLetter("A", "a", "啊"),
      italianLetter("B", "bi", "比"),
      italianLetter("C", "ci", "奇"),
      italianLetter("D", "di", "迪"),
      italianLetter("E", "e", "欸"),
      italianLetter("F", "effe", "艾費"),
      italianLetter("G", "gi", "吉"),
      italianLetter("H", "acca", "阿卡"),
      italianLetter("I", "i", "伊"),
      italianLetter("L", "elle", "艾雷"),
      italianLetter("M", "emme", "艾梅"),
      italianLetter("N", "enne", "艾內"),
      italianLetter("O", "o", "喔"),
      italianLetter("P", "pi", "皮"),
      italianLetter("Q", "cu", "庫"),
      italianLetter("R", "erre", "艾雷（顫音）"),
      italianLetter("S", "esse", "艾塞"),
      italianLetter("T", "ti", "提"),
      italianLetter("U", "u", "烏"),
      italianLetter("V", "vi / vu", "維／烏"),
      italianLetter("Z", "zeta", "澤塔"),
      italianLetter("J", "i lunga", "伊・倫加", "外來字母"),
      italianLetter("K", "cappa", "卡帕", "外來字母"),
      italianLetter("W", "doppia vu", "多皮亞・烏", "外來字母"),
      italianLetter("X", "ics", "伊克斯", "外來字母"),
      italianLetter("Y", "ipsilon", "伊普西隆", "外來字母"),
    ],
    phrases: [
      phraseItem("hello", "greetings", "你好", "Ciao!", "喬", "熟人間最常用的招呼。"),
      phraseItem("good-morning", "greetings", "早安", "Buongiorno!", "波恩・喬爾諾", "早晨到白天的禮貌招呼。"),
      phraseItem("good-afternoon", "greetings", "午安／下午好", "Buon pomeriggio!", "波恩・波梅里喬", "午後較正式的招呼。"),
      phraseItem("good-evening", "greetings", "晚上好", "Buonasera!", "波納・塞拉", "傍晚或夜間見面時。"),
      phraseItem("good-night", "greetings", "晚安", "Buonanotte!", "波納・諾特", "睡前或夜晚道別。"),
      phraseItem("goodbye", "greetings", "再見", "Arrivederci!", "阿里維德爾奇", "禮貌且通用的道別。"),
      phraseItem("see-you", "greetings", "回頭見", "A dopo!", "阿・多波", "和熟人輕鬆道別。"),
      phraseItem("nice-to-meet", "greetings", "很高興認識你", "Piacere di conoscerla.", "皮亞切雷・迪・科諾謝拉", "第一次見面的禮貌說法。"),
      phraseItem("please", "polite", "請", "Per favore.", "佩爾・法沃雷", "提出請求時使用。"),
      phraseItem("thanks", "polite", "謝謝", "Grazie!", "格拉茲耶", "最常用的謝謝。"),
      phraseItem("many-thanks", "polite", "非常謝謝", "Grazie mille!", "格拉茲耶・米雷", "加強謝意。"),
      phraseItem("you-are-welcome", "polite", "不客氣", "Prego!", "普雷果", "回應謝謝，也可表示請進。"),
      phraseItem("sorry", "polite", "對不起", "Mi dispiace.", "米・迪斯皮亞切", "較完整、真誠的道歉。"),
      phraseItem("excuse-me", "polite", "不好意思／打擾一下", "Scusi.", "斯庫西", "禮貌引起陌生人注意。"),
      phraseItem("no-problem", "polite", "沒關係", "Non fa niente.", "農・法・尼恩特", "表示不用在意。"),
      phraseItem("speak-english", "travel", "請問你會說英文嗎？", "Parla inglese?", "帕爾拉・英格雷澤", "禮貌詢問能否改用英文。"),
      phraseItem("dont-speak-language", "travel", "我不會說義大利語", "Non parlo italiano.", "農・帕爾洛・伊塔利亞諾", "先說明自己的語言能力。"),
      phraseItem("help-me", "travel", "可以請你幫我嗎？", "Mi può aiutare?", "米・普沃・阿尤塔雷", "需要一般協助時。"),
      phraseItem("how-much", "travel", "這個多少錢？", "Quanto costa questo?", "款托・科斯塔・奎斯托", "購物詢價時。"),
      phraseItem("want-this", "travel", "我要這個", "Prendo questo.", "普倫多・奎斯托", "購物時指著想要的物品。"),
      phraseItem("order", "restaurant", "我想點餐", "Vorrei ordinare.", "沃雷・奧爾迪納雷", "準備點餐時。"),
      phraseItem("menu", "restaurant", "請給我菜單", "Il menù, per favore.", "伊爾・梅努・佩爾・法沃雷", "向服務人員要菜單。"),
      phraseItem("bill", "restaurant", "我要結帳", "Il conto, per favore.", "伊爾・孔托・佩爾・法沃雷", "用餐後請服務人員結帳。"),
      phraseItem("toilet", "travel", "洗手間在哪裡？", "Dov'è il bagno?", "多韋・伊爾・巴紐", "尋找洗手間。"),
      phraseItem("station", "transport", "車站在哪裡？", "Dov'è la stazione?", "多韋・拉・斯塔齊奧內", "詢問火車站位置。"),
      phraseItem("lost", "travel", "我迷路了", "Mi sono perso.", "米・索諾・佩爾索", "迷路時使用；女性可說 persa。"),
      phraseItem("slower", "travel", "請慢一點說", "Può parlare più lentamente?", "普沃・帕爾拉雷・皮烏・倫塔門特", "對方說得太快時。"),
      phraseItem("repeat", "travel", "可以再說一次嗎？", "Può ripetere, per favore?", "普沃・里佩特雷・佩爾・法沃雷", "沒有聽清楚時。"),
      phraseItem("reservation", "accommodation", "我有預約", "Ho una prenotazione.", "奧・烏納・普雷諾塔齊奧內", "飯店或餐廳報到時。"),
      phraseItem("go-here", "transport", "我想去這裡", "Vorrei andare qui.", "沃雷・安達雷・奎", "指著地圖告訴司機。"),
      phraseItem("call-taxi", "transport", "請幫我叫計程車", "Può chiamarmi un taxi?", "普沃・基亞馬爾米・溫・塔克西", "請櫃檯或店員叫車。"),
      phraseItem("ticket", "transport", "請給我一張到市中心的票", "Un biglietto per il centro, per favore.", "溫・比列托・佩爾・伊爾・千特羅・佩爾・法沃雷", "在售票處買票。"),
      phraseItem("platform", "transport", "請問是第幾月台？", "Quale binario, per favore?", "夸雷・比納里奧・佩爾・法沃雷", "確認列車月台。"),
      phraseItem("check-in", "accommodation", "我想辦理入住", "Vorrei fare il check-in.", "沃雷・法雷・伊爾・切克因", "抵達飯店櫃檯時。"),
      phraseItem("wifi", "accommodation", "這裡有 Wi-Fi 嗎？", "C'è il Wi-Fi?", "切・伊爾・外法以", "詢問網路服務。"),
      phraseItem("allergy", "restaurant", "我對堅果過敏", "Sono allergico alla frutta a guscio.", "索諾・阿萊爾吉科・阿拉・弗魯塔・阿・古修", "用餐前說明過敏；女性可說 allergica。"),
    ],
    numberRules: {
      coreNumbers: [
        numberRuleItem("0", "zero", "零", "傑羅", "", "", "core"),
        numberRuleItem("1", "uno", "一", "烏諾", "", "", "core"),
        numberRuleItem("2", "due", "二", "杜欸", "", "", "core"),
        numberRuleItem("3", "tre", "三", "特雷", "", "", "core"),
        numberRuleItem("4", "quattro", "四", "夸特羅", "", "", "core"),
        numberRuleItem("5", "cinque", "五", "欽奎", "", "", "core"),
        numberRuleItem("6", "sei", "六", "賽", "", "", "core"),
        numberRuleItem("7", "sette", "七", "塞特", "", "", "core"),
        numberRuleItem("8", "otto", "八", "奧托", "", "", "core"),
        numberRuleItem("9", "nove", "九", "諾維", "", "", "core"),
        numberRuleItem("10", "dieci", "十", "迪耶奇", "", "", "core"),
        numberRuleItem("11", "undici", "十一", "溫迪奇", "", "", "core"),
        numberRuleItem("12", "dodici", "十二", "多迪奇", "", "", "core"),
        numberRuleItem("13", "tredici", "十三", "特雷迪奇", "", "", "core"),
        numberRuleItem("14", "quattordici", "十四", "夸托爾迪奇", "", "", "core"),
        numberRuleItem("15", "quindici", "十五", "昆迪奇", "", "", "core"),
        numberRuleItem("16", "sedici", "十六", "塞迪奇", "", "", "core"),
        numberRuleItem("17", "diciassette", "十七", "迪恰塞特", "", "", "core"),
        numberRuleItem("18", "diciotto", "十八", "迪裘托", "", "", "core"),
        numberRuleItem("19", "diciannove", "十九", "迪恰諾維", "", "", "core"),
      ],
      tens: [
        numberRuleItem("20", "venti", "二十", "文提", "", "", "tens"),
        numberRuleItem("30", "trenta", "三十", "特倫塔", "", "", "tens"),
        numberRuleItem("40", "quaranta", "四十", "夸蘭塔", "", "", "tens"),
        numberRuleItem("50", "cinquanta", "五十", "欽款塔", "", "", "tens"),
        numberRuleItem("60", "sessanta", "六十", "塞桑塔", "", "", "tens"),
        numberRuleItem("70", "settanta", "七十", "塞坦塔", "", "", "tens"),
        numberRuleItem("80", "ottanta", "八十", "奧坦塔", "", "", "tens"),
        numberRuleItem("90", "novanta", "九十", "諾萬塔", "", "", "tens"),
        numberRuleItem("100", "cento", "一百", "千托", "", "", "tens"),
      ],
      rules: [
        {
          title: "基本組合方向",
          formula: "十位數 + 個位數",
          description: "義大利語 21 以後通常由十位數接個位數，方向和中文接近。",
        },
        { title: "22", formula: "venti + due → ventidue", description: "二十加二。" },
        { title: "35", formula: "trenta + cinque → trentacinque", description: "三十加五。" },
        { title: "46", formula: "quaranta + sei → quarantasei", description: "四十加六。" },
        { title: "57", formula: "cinquanta + sette → cinquantasette", description: "五十加七。" },
        { title: "99", formula: "novanta + nove → novantanove", description: "九十加九。" },
      ],
      exceptions: [
        { title: "1 與 8 前省略母音", text: "十位數後接 uno 或 otto 時，通常去掉十位數最後的母音。" },
        { title: "21 / 28", text: "venti + uno → ventuno；venti + otto → ventotto。" },
        { title: "31 / 38", text: "trenta + uno → trentuno；trenta + otto → trentotto。" },
        { title: "41 / 48", text: "quaranta + uno → quarantuno；quaranta + otto → quarantotto。" },
        { title: "81 / 88", text: "ottanta + uno → ottantuno；ottanta + otto → ottantotto。" },
        { title: "100 以後", text: "100 是 cento；101 可寫作 centouno。" },
      ],
      decimalRules: {
        separatorName: "virgola",
        separatorSymbol: ",",
        readingRule: "整數 + virgola + 小數部分",
        description: "義大利語小數逗號後可以讀成一整個數字，也可以逐位讀出。旅行情境中，先學會 virgola 的用法即可。",
        examples: [
          decimalExample("3,14", "tre virgola quattordici", "三點一四", "小數逗號後可讀成一整個數字；逐位也可說 tre virgola uno quattro。"),
          decimalExample("1,5", "uno virgola cinque", "一點五", "相當於中文的小數點。"),
          decimalExample("0,8", "zero virgola otto", "零點八", "相當於中文的小數點。"),
          decimalExample("12,75", "dodici virgola settantacinque", "十二點七五", "小數部分也可以逐位讀出。"),
        ],
      },
      examples: [
        numberRuleItem("21", "ventuno", "二十一", "文圖諾", "venti + uno", "省略 venti 最後的 i。", "example"),
        numberRuleItem("22", "ventidue", "二十二", "文提・杜欸", "venti + due", "", "example"),
        numberRuleItem("28", "ventotto", "二十八", "文托托", "venti + otto", "省略 venti 最後的 i。", "example"),
        numberRuleItem("31", "trentuno", "三十一", "特倫圖諾", "trenta + uno", "省略 trenta 最後的 a。", "example"),
        numberRuleItem("35", "trentacinque", "三十五", "特倫塔・欽奎", "trenta + cinque", "", "example"),
        numberRuleItem("48", "quarantotto", "四十八", "夸蘭托托", "quaranta + otto", "省略 quaranta 最後的 a。", "example"),
        numberRuleItem("57", "cinquantasette", "五十七", "欽款塔・塞特", "cinquanta + sette", "", "example"),
        numberRuleItem("81", "ottantuno", "八十一", "奧坦圖諾", "ottanta + uno", "省略 ottanta 最後的 a。", "example"),
        numberRuleItem("88", "ottantotto", "八十八", "奧坦托托", "ottanta + otto", "省略 ottanta 最後的 a。", "example"),
        numberRuleItem("99", "novantanove", "九十九", "諾萬塔・諾維", "novanta + nove", "", "example"),
      ],
    },
  },
};
